name: "Trigger Workflow and Wait"
description: "A GitHub Action to trigger a workflow and wait for its completion."
inputs:
  owner:
    description: "The owner of the repository."
    required: true
  repo:
    description: "The name of the repository."
    required: true
  github_token:
    description: "GitHub token with repo access."
    required: true
  workflow_file_name:
    description: "The name of the workflow file to trigger."
    required: true
  wait_interval:
    description: "The interval to wait between checks (in seconds)."
    required: false
    default: "10"
  propagate_failure:
    description: "Whether to propagate failure to the upstream job."
    required: false
    default: "true"
  trigger_workflow:
    description: "Whether to trigger the workflow."
    required: false
    default: "true"
  wait_workflow:
    description: "Whether to wait for the workflow to finish."
    required: false
    default: "true"
outputs:
  workflow_id:
    description: "The ID of the triggered workflow."
  workflow_url:
    description: "The URL of the triggered workflow."
runs:
  using: "node20"
  main: "dist/index.js"