name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run tests with coverage
      run: npm run test:coverage
    
    - name: Build action
      run: npm run build:complete
    
    - name: Check if build produces changes
      id: check_changes
      run: |
        # Check if there are any changes after build
        if git diff --quiet index.js; then
          echo "No changes detected in index.js after build"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected in index.js after build"
          git diff index.js
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

  coverage-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests with coverage
      run: npm run test:coverage
    
    - name: Build action
      run: npm run build:complete
