name: Test Action

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test the action
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test action (dry run)
        uses: ./
        with:
          owner: 'greedigoblins'
          repo: 'trigger-workflow-and-wait'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: 'ci.yml'
          trigger_workflow: 'false'  # Don't actually trigger
          wait_workflow: 'false'     # Don't wait
        env:
          INPUT_OWNER: 'greedigoblins'
          INPUT_REPO: 'trigger-workflow-and-wait'
